<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?= $title ?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <div class="container">
    <header>
      <h1><?= $title ?></h1>
      <h2 style='visibility: hidden' id="templateID"><?= $templateName?><h2>
    </header>
    <template id="loginFormTemplate">
    
      <form action="POST" id="loginForm">
       <h4>Login to access REDDITv2</h4>
       <p>Login: <input type="text" id="logName" required><p>
       <p>Password: <input type="password" id="logPassword" required></p>
       <input class="btn-primary" type="submit" id="login" value="Login"><br>
       <a href="#" id="registerButton">Dont have an account? register</a>
       </form>
       </template>
    <template id="registerTemplate">
       <form action="POST" id="regForm">
       <h4>Registrate new account</h4>
       <p id="RegMessage"></p>
       <p>Login: <input type="text" id="regName" required><p>
       <p>Password: <input type="password" id="regPassword" required></p>
       <input class="btn-primary" type="submit" id="reg" value="Register">
       </form>
     </template>

    <template id="inloggedAllEntryes">
     <div class="container text-center">
     <nav id=someNav class="navbar navbar-light bg-light">
     
      <button class="navbar-brand btn-primary" id="addEntry">AddNewEntry</button>
      <button class="navbar-brand" id="myEntr">ShowMyEntries</button>
      <button class="navbar-brand " id="LogOut">Logout</button>
     </nav>
     
     <p>Tittle: <input type=text id=uTitle><button id=Search>Search</button></p>
     <h2 id=SideTitle>All entryes</h2>
     <div id=pageNum>
     <a id="page1" href="#">1</a>
     </div>
     <table class="table text-center">
     <tbody id="entryBody">
     </tbody>
     </table>
     </template>
    <!-- SingleEntry -->
    <template id="singleentry">
     <h1 id=UserName style="visibility:hidden"><?=$_SESSION['UName']?></h1>
     <button id=homeBTN>home</button>
     <h1 id=seTitle></h1>
     <p style=visibility:hidden id=eID>
     <p id="eECID"></p>
     <p>Comment Part<p>
     <p id="eComments"></p>
     <table class="table">
     <tbody id="CommentSection">
     </tbody>
     </table>
     
     <form action="POST" id="CommentForm">
       
       <p>Comment Text</p> <textarea id=eContent rows="4" cols="30"></textarea><br>
       <input type="submit" id="createComment" value="Add comment">
     </form>
     </div>
     </template>
   <template id=AddEntryTemplate>
    <!-- style="visibility:hidden -->
    <button id=homeBTN>home</button>
    <form action="POST" id="addEntForm">
    <p>Tittle: <input type=text id=eTitle><br></p>
    <p>Content:</p> <textarea id=eContent rows="4" cols="50"></textarea>
    <input type="submit" id="createEntry" value="Add new Entry">
    </form>


    </template>
   <template id="uppdateEntry">
    <form action="POST" id="UppdateForm">
    <p style="visibility: hidden" id=thisID><p>
    <p>Tittle: <input type=text id=uTitle><br></p>
    <p>Content:</p> <textarea id=uContent rows="4" cols="50"></textarea>
    <input type="submit" id="updateEntry" value="Uppdate">
    </form>


    </template>
    <main>
      <!-- INNEHÅLL -->
    </main>
  </div>
  <script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  <script type="text/javascript" src="main.js"></script>
</body>

</html>